//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LynxTranscribe.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LynxTranscribe.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accurate.
        /// </summary>
        internal static string Accurate {
            get {
                return ResourceManager.GetString("Accurate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribed using Accurate mode for higher quality results.
        /// </summary>
        internal static string AccurateModeTooltip {
            get {
                return ResourceManager.GetString("AccurateModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply dictation formatting.
        /// </summary>
        internal static string ApplyDictationFormatting {
            get {
                return ResourceManager.GetString("ApplyDictationFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LynxTranscribe.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.0.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file not found.
        /// </summary>
        internal static string AudioFileNotFound {
            get {
                return ResourceManager.GetString("AudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Input.
        /// </summary>
        internal static string AudioInput {
            get {
                return ResourceManager.GetString("AudioInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone for recording.
        /// </summary>
        internal static string AudioInputDescription {
            get {
                return ResourceManager.GetString("AudioInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-transcribe on import.
        /// </summary>
        internal static string AutoTranscribeOnImport {
            get {
                return ResourceManager.GetString("AutoTranscribeOnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically begin transcription when audio is loaded.
        /// </summary>
        internal static string AutoTranscribeOnImportDescription {
            get {
                return ResourceManager.GetString("AutoTranscribeOnImportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend.
        /// </summary>
        internal static string Backend {
            get {
                return ResourceManager.GetString("Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        internal static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all transcription history? This cannot be undone..
        /// </summary>
        internal static string ClearHistoryMessage {
            get {
                return ResourceManager.GetString("ClearHistoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        internal static string ClearHistoryTitle {
            get {
                return ResourceManager.GetString("ClearHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to skip.
        /// </summary>
        internal static string ClickToSkip {
            get {
                return ResourceManager.GetString("ClickToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to skip countdown.
        /// </summary>
        internal static string ClickToSkipCountdown {
            get {
                return ResourceManager.GetString("ClickToSkipCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Transcribe to start.
        /// </summary>
        internal static string ClickTranscribeToStart {
            get {
                return ResourceManager.GetString("ClickTranscribeToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (Escape).
        /// </summary>
        internal static string CloseEscape {
            get {
                return ResourceManager.GetString("CloseEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        internal static string Confidence {
            get {
                return ResourceManager.GetString("Confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert speech to text in seconds.
        /// </summary>
        internal static string ConvertSpeechToText {
            get {
                return ResourceManager.GetString("ConvertSpeechToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy transcript to clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect audio input device.
        /// </summary>
        internal static string CouldNotDetectAudioDevice {
            get {
                return ResourceManager.GetString("CouldNotDetectAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect LM-Kit backend.
        /// </summary>
        internal static string CouldNotDetectBackend {
            get {
                return ResourceManager.GetString("CouldNotDetectBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open file location: {0}.
        /// </summary>
        internal static string CouldNotOpenFileLocation {
            get {
                return ResourceManager.GetString("CouldNotOpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open folder: {0}.
        /// </summary>
        internal static string CouldNotOpenFolder {
            get {
                return ResourceManager.GetString("CouldNotOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between light and dark theme.
        /// </summary>
        internal static string DarkModeDescription {
            get {
                return ResourceManager.GetString("DarkModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease font size.
        /// </summary>
        internal static string DecreaseFontSize {
            get {
                return ResourceManager.GetString("DecreaseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this transcription from history?.
        /// </summary>
        internal static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictation.
        /// </summary>
        internal static string Dictation {
            get {
                return ResourceManager.GetString("Dictation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brackets &amp; Parentheses.
        /// </summary>
        internal static string DictationCategoryBrackets {
            get {
                return ResourceManager.GetString("DictationCategoryBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Breaks.
        /// </summary>
        internal static string DictationCategoryLineBreaks {
            get {
                return ResourceManager.GetString("DictationCategoryLineBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation.
        /// </summary>
        internal static string DictationCategoryPunctuation {
            get {
                return ResourceManager.GetString("DictationCategoryPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation + Line Break.
        /// </summary>
        internal static string DictationCategoryPunctuationLineBreak {
            get {
                return ResourceManager.GetString("DictationCategoryPunctuationLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Marks.
        /// </summary>
        internal static string DictationCategoryQuotes {
            get {
                return ResourceManager.GetString("DictationCategoryQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        internal static string DictationCategorySymbols {
            get {
                return ResourceManager.GetString("DictationCategorySymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Formatting.
        /// </summary>
        internal static string DictationCategoryTextFormatting {
            get {
                return ResourceManager.GetString("DictationCategoryTextFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictation Commands.
        /// </summary>
        internal static string DictationCommands {
            get {
                return ResourceManager.GetString("DictationCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say these words to insert formatting.
        /// </summary>
        internal static string DictationCommandsSubtitle {
            get {
                return ResourceManager.GetString("DictationCommandsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictation formatting.
        /// </summary>
        internal static string DictationFormatting {
            get {
                return ResourceManager.GetString("DictationFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert spoken commands (period, comma, new line).
        /// </summary>
        internal static string DictationFormattingDescription {
            get {
                return ResourceManager.GetString("DictationFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert spoken commands to punctuation (period, comma, new line).
        /// </summary>
        internal static string DictationTooltip {
            get {
                return ResourceManager.GetString("DictationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to play.
        /// </summary>
        internal static string DoubleClickToPlay {
            get {
                return ResourceManager.GetString("DoubleClickToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}....
        /// </summary>
        internal static string DownloadingModel {
            get {
                return ResourceManager.GetString("DownloadingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading model....
        /// </summary>
        internal static string DownloadingModelProgress {
            get {
                return ResourceManager.GetString("DownloadingModelProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop audio file here.
        /// </summary>
        internal static string DropAudioFileHere {
            get {
                return ResourceManager.GetString("DropAudioFileHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0}s elapsed.
        /// </summary>
        internal static string Elapsed {
            get {
                return ResourceManager.GetString("Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m {1}s elapsed.
        /// </summary>
        internal static string ElapsedMinutes {
            get {
                return ResourceManager.GetString("ElapsedMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to TXT, DOCX, RTF, SRT or VTT.
        /// </summary>
        internal static string ExportTooltip {
            get {
                return ResourceManager.GetString("ExportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Transcript.
        /// </summary>
        internal static string ExportTranscript {
            get {
                return ResourceManager.GetString("ExportTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start recording: {0}.
        /// </summary>
        internal static string FailedToStartRecording {
            get {
                return ResourceManager.GetString("FailedToStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in transcript....
        /// </summary>
        internal static string FindInTranscript {
            get {
                return ResourceManager.GetString("FindInTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ready....
        /// </summary>
        internal static string GetReady {
            get {
                return ResourceManager.GetString("GetReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Directory.
        /// </summary>
        internal static string HistoryDirectory {
            get {
                return ResourceManager.GetString("HistoryDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where transcription history is stored.
        /// </summary>
        internal static string HistoryDirectoryDescription {
            get {
                return ResourceManager.GetString("HistoryDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History directory updated.
        /// </summary>
        internal static string HistoryDirectoryUpdated {
            get {
                return ResourceManager.GetString("HistoryDirectoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase font size.
        /// </summary>
        internal static string IncreaseFontSize {
            get {
                return ResourceManager.GetString("IncreaseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred language.
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LM-Kit.
        /// </summary>
        internal static string LMKit {
            get {
                return ResourceManager.GetString("LMKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LM-Kit Runtime Backend: {0}.
        /// </summary>
        internal static string LMKitBackend {
            get {
                return ResourceManager.GetString("LMKitBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}....
        /// </summary>
        internal static string LoadingModel {
            get {
                return ResourceManager.GetString("LoadingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} MB required.
        /// </summary>
        internal static string MBRequired {
            get {
                return ResourceManager.GetString("MBRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Directory.
        /// </summary>
        internal static string ModelDirectory {
            get {
                return ResourceManager.GetString("ModelDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where AI models are stored.
        /// </summary>
        internal static string ModelDirectoryDescription {
            get {
                return ResourceManager.GetString("ModelDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model directory updated.
        /// </summary>
        internal static string ModelDirectoryUpdated {
            get {
                return ResourceManager.GetString("ModelDirectoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next match (Enter).
        /// </summary>
        internal static string NextMatch {
            get {
                return ResourceManager.GetString("NextMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device.
        /// </summary>
        internal static string NoAudioDevice {
            get {
                return ResourceManager.GetString("NoAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio input device available.
        /// </summary>
        internal static string NoAudioDeviceAvailable {
            get {
                return ResourceManager.GetString("NoAudioDeviceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device.
        /// </summary>
        internal static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history yet.
        /// </summary>
        internal static string NoHistoryYet {
            get {
                return ResourceManager.GetString("NoHistoryYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Mic.
        /// </summary>
        internal static string NoMic {
            get {
                return ResourceManager.GetString("NoMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transcript to search.
        /// </summary>
        internal static string NoTranscriptToSearch {
            get {
                return ResourceManager.GetString("NoTranscriptToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file after export.
        /// </summary>
        internal static string OpenFileAfterExport {
            get {
                return ResourceManager.GetString("OpenFileAfterExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file location.
        /// </summary>
        internal static string OpenFileLocation {
            get {
                return ResourceManager.GetString("OpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file location is only available on Windows.
        /// </summary>
        internal static string OpenFileLocationWindowsOnly {
            get {
                return ResourceManager.GetString("OpenFileLocationWindowsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open files after export.
        /// </summary>
        internal static string OpenFilesAfterExport {
            get {
                return ResourceManager.GetString("OpenFilesAfterExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically open exported files in default app.
        /// </summary>
        internal static string OpenFilesAfterExportDescription {
            get {
                return ResourceManager.GetString("OpenFilesAfterExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or browse files / record audio.
        /// </summary>
        internal static string OrBrowseFilesRecordAudio {
            get {
                return ResourceManager.GetString("OrBrowseFilesRecordAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string PerformanceSettings {
            get {
                return ResourceManager.GetString("PerformanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string PlainText {
            get {
                return ResourceManager.GetString("PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt - Simple text format.
        /// </summary>
        internal static string PlainTextDescription {
            get {
                return ResourceManager.GetString("PlainTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback speed: {0}x.
        /// </summary>
        internal static string PlaybackSpeed {
            get {
                return ResourceManager.GetString("PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback speed: {0}x.
        /// </summary>
        internal static string PlaybackSpeedFormat {
            get {
                return ResourceManager.GetString("PlaybackSpeedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        internal static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Esc to close.
        /// </summary>
        internal static string PressEscToClose {
            get {
                return ResourceManager.GetString("PressEscToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous match (Shift+Enter).
        /// </summary>
        internal static string PreviousMatch {
            get {
                return ResourceManager.GetString("PreviousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processed in {0:F1}s.
        /// </summary>
        internal static string ProcessedIn {
            get {
                return ResourceManager.GetString("ProcessedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processed in {0}m {1:F0}s.
        /// </summary>
        internal static string ProcessedInMinutes {
            get {
                return ResourceManager.GetString("ProcessedInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to transcribe.
        /// </summary>
        internal static string ReadyToTranscribe {
            get {
                return ResourceManager.GetString("ReadyToTranscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        internal static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording cancelled.
        /// </summary>
        internal static string RecordingCancelled {
            get {
                return ResourceManager.GetString("RecordingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording error: {0}.
        /// </summary>
        internal static string RecordingError {
            get {
                return ResourceManager.GetString("RecordingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording saved.
        /// </summary>
        internal static string RecordingSaved {
            get {
                return ResourceManager.GetString("RecordingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings Directory.
        /// </summary>
        internal static string RecordingsDirectory {
            get {
                return ResourceManager.GetString("RecordingsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where audio recordings are saved.
        /// </summary>
        internal static string RecordingsDirectoryDescription {
            get {
                return ResourceManager.GetString("RecordingsDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings directory updated.
        /// </summary>
        internal static string RecordingsDirectoryUpdated {
            get {
                return ResourceManager.GetString("RecordingsDirectoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording started.
        /// </summary>
        internal static string RecordingStarted {
            get {
                return ResourceManager.GetString("RecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~{0}s remaining.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~{0}m {1}s remaining.
        /// </summary>
        internal static string RemainingMinutes {
            get {
                return ResourceManager.GetString("RemainingMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new name for this transcription:.
        /// </summary>
        internal static string RenameMessage {
            get {
                return ResourceManager.GetString("RenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameTitle {
            get {
                return ResourceManager.GetString("RenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset all settings to their default values. Are you sure?.
        /// </summary>
        internal static string ResetConfirmMessage {
            get {
                return ResourceManager.GetString("ResetConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        internal static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string ResourceLevelBalanced {
            get {
                return ResourceManager.GetString("ResourceLevelBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ResourceLevelLight {
            get {
                return ResourceManager.GetString("ResourceLevelLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string ResourceLevelMaximum {
            get {
                return ResourceManager.GetString("ResourceLevelMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string ResourceLevelPerformance {
            get {
                return ResourceManager.GetString("ResourceLevelPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Resource Usage.
        /// </summary>
        internal static string ResourceUsage {
            get {
                return ResourceManager.GetString("ResourceUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU threads allocated for transcription.
        /// </summary>
        internal static string ResourceUsageDescription {
            get {
                return ResourceManager.GetString("ResourceUsageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart from beginning.
        /// </summary>
        internal static string RestartPlayback {
            get {
                return ResourceManager.GetString("RestartPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text.
        /// </summary>
        internal static string RichText {
            get {
                return ResourceManager.GetString("RichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rtf - Formatted text with styling.
        /// </summary>
        internal static string RichTextDescription {
            get {
                return ResourceManager.GetString("RichTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved to {0}.
        /// </summary>
        internal static string SavedTo {
            get {
                return ResourceManager.GetString("SavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search history....
        /// </summary>
        internal static string SearchHistory {
            get {
                return ResourceManager.GetString("SearchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in transcript (Ctrl+F).
        /// </summary>
        internal static string SearchInTranscript {
            get {
                return ResourceManager.GetString("SearchInTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SegmentLanguage {
            get {
                return ResourceManager.GetString("SegmentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} segments.
        /// </summary>
        internal static string Segments {
            get {
                return ResourceManager.GetString("Segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or drop an audio file.
        /// </summary>
        internal static string SelectOrDropAudioFile {
            get {
                return ResourceManager.GetString("SelectOrDropAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings reset to defaults.
        /// </summary>
        internal static string SettingsResetToDefaults {
            get {
                return ResourceManager.GetString("SettingsResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dictation commands.
        /// </summary>
        internal static string ShowDictationCommands {
            get {
                return ResourceManager.GetString("ShowDictationCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster.
        /// </summary>
        internal static string SpeedFaster {
            get {
                return ResourceManager.GetString("SpeedFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to 1×.
        /// </summary>
        internal static string SpeedReset {
            get {
                return ResourceManager.GetString("SpeedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slower.
        /// </summary>
        internal static string SpeedSlower {
            get {
                return ResourceManager.GetString("SpeedSlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRT Subtitles.
        /// </summary>
        internal static string SrtSubtitles {
            get {
                return ResourceManager.GetString("SrtSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .srt - Timed subtitles for video.
        /// </summary>
        internal static string SrtSubtitlesDescription {
            get {
                return ResourceManager.GetString("SrtSubtitlesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LynxTranscribe v1.0 - Powered by LM-Kit.
        /// </summary>
        internal static string StatusBarInfo {
            get {
                return ResourceManager.GetString("StatusBarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        internal static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Locations.
        /// </summary>
        internal static string StorageLocations {
            get {
                return ResourceManager.GetString("StorageLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports WAV, MP3, FLAC, OGG, M4A.
        /// </summary>
        internal static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to dark mode.
        /// </summary>
        internal static string SwitchToDarkMode {
            get {
                return ResourceManager.GetString("SwitchToDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to light mode.
        /// </summary>
        internal static string SwitchToLightMode {
            get {
                return ResourceManager.GetString("SwitchToLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} timestamps.
        /// </summary>
        internal static string TimestampsCount {
            get {
                return ResourceManager.GetString("TimestampsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribe.
        /// </summary>
        internal static string Transcribe {
            get {
                return ResourceManager.GetString("Transcribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribing....
        /// </summary>
        internal static string Transcribing {
            get {
                return ResourceManager.GetString("Transcribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript.
        /// </summary>
        internal static string Transcript {
            get {
                return ResourceManager.GetString("Transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription cancelled.
        /// </summary>
        internal static string TranscriptionCancelled {
            get {
                return ResourceManager.GetString("TranscriptionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription complete.
        /// </summary>
        internal static string TranscriptionComplete {
            get {
                return ResourceManager.GetString("TranscriptionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription Failed.
        /// </summary>
        internal static string TranscriptionFailed {
            get {
                return ResourceManager.GetString("TranscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription Language.
        /// </summary>
        internal static string TranscriptionLanguageSetting {
            get {
                return ResourceManager.GetString("TranscriptionLanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language for speech recognition.
        /// </summary>
        internal static string TranscriptionLanguageSettingDescription {
            get {
                return ResourceManager.GetString("TranscriptionLanguageSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription Mode.
        /// </summary>
        internal static string TranscriptionModeSetting {
            get {
                return ResourceManager.GetString("TranscriptionModeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance between speed and accuracy.
        /// </summary>
        internal static string TranscriptionModeSettingDescription {
            get {
                return ResourceManager.GetString("TranscriptionModeSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription.
        /// </summary>
        internal static string TranscriptionSettings {
            get {
                return ResourceManager.GetString("TranscriptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcriptions will appear here.
        /// </summary>
        internal static string TranscriptionsWillAppearHere {
            get {
                return ResourceManager.GetString("TranscriptionsWillAppearHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo.
        /// </summary>
        internal static string Turbo {
            get {
                return ResourceManager.GetString("Turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribed using Turbo mode for faster processing.
        /// </summary>
        internal static string TurboModeTooltip {
            get {
                return ResourceManager.GetString("TurboModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using: {0}.
        /// </summary>
        internal static string UsingMicrophone {
            get {
                return ResourceManager.GetString("UsingMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0} of {1} threads.
        /// </summary>
        internal static string UsingThreads {
            get {
                return ResourceManager.GetString("UsingThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAD.
        /// </summary>
        internal static string VAD {
            get {
                return ResourceManager.GetString("VAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Activity Detection was enabled - silence and non-speech audio were filtered out.
        /// </summary>
        internal static string VadBadgeTooltip {
            get {
                return ResourceManager.GetString("VadBadgeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter out silence and non-speech audio.
        /// </summary>
        internal static string VadDescription {
            get {
                return ResourceManager.GetString("VadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Activity Detection is disabled - all audio will be transcribed.
        /// </summary>
        internal static string VadDisabled {
            get {
                return ResourceManager.GetString("VadDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Activity Detection is enabled - silence and non-speech audio will be filtered out.
        /// </summary>
        internal static string VadEnabled {
            get {
                return ResourceManager.GetString("VadEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Activity Detection was enabled - silence and non-speech audio were filtered out.
        /// </summary>
        internal static string VadEnabledNotice {
            get {
                return ResourceManager.GetString("VadEnabledNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Activity Detection - Filters out silence and non-speech audio.
        /// </summary>
        internal static string VadTooltip {
            get {
                return ResourceManager.GetString("VadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string ViewModeDocument {
            get {
                return ResourceManager.GetString("ViewModeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segments.
        /// </summary>
        internal static string ViewModeSegments {
            get {
                return ResourceManager.GetString("ViewModeSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Activity Detection.
        /// </summary>
        internal static string VoiceActivityDetection {
            get {
                return ResourceManager.GetString("VoiceActivityDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebVTT Subtitles.
        /// </summary>
        internal static string WebVttSubtitles {
            get {
                return ResourceManager.GetString("WebVttSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vtt - Web video text tracks.
        /// </summary>
        internal static string WebVttSubtitlesDescription {
            get {
                return ResourceManager.GetString("WebVttSubtitlesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Document.
        /// </summary>
        internal static string WordDocument {
            get {
                return ResourceManager.GetString("WordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .docx - Microsoft Word format.
        /// </summary>
        internal static string WordDocumentDescription {
            get {
                return ResourceManager.GetString("WordDocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} words.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} words (partial).
        /// </summary>
        internal static string WordsPartial {
            get {
                return ResourceManager.GetString("WordsPartial", resourceCulture);
            }
        }
    }
}
